import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils"; 
import Nav from "@/src/components/Nav";
import Providers from "@/src/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <Providers>
      <body
        className={cn(
          "min-h-screen grainy font-sans antialiased",
          inter.className
        )}
      >
        <Nav/>
        {children}
      </body>
      </Providers>
    </html>
  );
}
